### ISSUE TITLE
来催催了，在进入 /auth 后 `跳转链接` 选项为空

### ISSUE THREAD

**Issue by valetzx** [arect/o-blog#1]
![image](https://user-images.githubusercontent.com/45054400/184267413-591b9012-40fe-4c4e-a29c-5f5d97f95bf5.png)
主页一直在获取数据，可能是reftoken的问题？
![image](https://user-images.githubusercontent.com/45054400/184267568-5dfddb87-903d-4361-9dd6-d0c42823be3b.png)
在回调后是否会自动储存reftoken呢，要不要手动改后台的环境

**Comment by arect** [comment]
不会自动储存的，需要再填入环境变量再次部署。
这个可能有点问题，我到时候改成自己填吧。
最近刚上班有点忙，近期找时间完善完善。

**Comment by valetzx** [comment]
好的，感谢

**Comment by valetzx** [comment]
https://oblog.pigp.repl.co 这是我暂时测试的网站
好像不是reftoken的问题，这是f12控制台报错
```
ixed Content: The page at 'https://oblog.pigp.repl.co/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://oblog.pigp.repl.co:24678/_nuxt/'. This request has been blocked; this endpoint must be available over WSS.
(匿名) @ client.ts:22
Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at https://oblog.pigp.repl.co/_nuxt/@vite/client:188:16
```

**Comment by valetzx** [comment]
已解决，npm run dev 会有 ws问题
解决方法是构建一份后 用 preview 预览

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/184469508-9e86bc8e-f56e-452e-8ac0-bbe60a8b21a5.png)
但是获取文章时返回了一堆null

**Comment by arect** [comment]
文章名用了新格式，你看看是不是没改？
`[1][文章名][tag1;tag2]`

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/184469596-64800803-343e-4cbe-8b27-73a30ef47e7e.png)
改过了 [000][Replit监控][白嫖;教程][color_light]，你访问上面的网页看看有没有什么问题

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/184469639-c112ee35-0d90-4328-92e7-791b79bbfe6c.png)
读出页数了 没渲染？？

**Comment by valetzx** [comment]
嗷嗷不好意思，根目录settings没改

**Comment by arect** [comment]
啊？settings还有这种能力？
咋回事啊？

**Comment by valetzx** [comment]
额，但是所有文章都下载错误？ 获取信息失败

**Comment by arect** [comment]
我打个log提交一下，你看看后台输出

**Comment by valetzx** [comment]
好的，方便加个联系方式吗（）

**Comment by arect** [comment]
https://onedrive-blog.vercel.app/article/01DXDGLDHDVDTVSVUDKZALTDEKMJ7CXU25
见内容

**Comment by valetzx** [comment]
收到
